// Regenerates data/leetcode.js: the LeetCode number, slug and Premium flag of every problem.
// Needs network, so it is a manual tool and not part of `npm test`.   Run:  node scripts/leetcode-links.mjs
//
// NeetCode's own data supplies the slugs; LeetCode's public GraphQL endpoint confirms each one exists and
// says whether it is Premium. It stops without writing anything if a problem is unmatched, a slug does not
// exist, or the difficulty disagrees with ours.

import { writeFileSync } from 'node:fs';
import { RAW_TOPICS } from '../data/topics.js';
import { problemId } from '../data/ids.js';

const SOURCE = 'https://raw.githubusercontent.com/neetcode-gh/leetcode/main/.problemSiteData.json';
const OUT = new URL('../data/leetcode.js', import.meta.url);
const QUERY = 'query q($s:String!){question(titleSlug:$s){questionFrontendId title isPaidOnly difficulty}}';
const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '');

async function getJson(url, init, tries = 3) {
  for (let i = 1; ; i++) {
    try {
      const res = await fetch(url, init);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (e) {
      if (i >= tries) throw new Error(`${url}: ${e.message}`);
      await new Promise((r) => setTimeout(r, 500 * i));
    }
  }
}

const neet = new Map((await getJson(SOURCE)).filter((p) => p.neetcode150).map((p) => [norm(p.problem), p]));
const entries = [];
const problems = [];

for (const t of RAW_TOPICS) {
  for (const g of t.groups) {
    for (const [name, diff] of g.items) {
      const src = neet.get(norm(name));
      if (!src) throw new Error(`No NeetCode entry for "${name}" (${t.id})`);
      const slug = src.link.replace(/\/$/, '');
      const data = await getJson('https://leetcode.com/graphql', {
        method: 'POST',
        headers: { 'content-type': 'application/json', referer: 'https://leetcode.com', 'user-agent': 'Mozilla/5.0' },
        body: JSON.stringify({ query: QUERY, variables: { s: slug } }),
      });
      const q = data.data.question;
      if (!q) throw new Error(`LeetCode has no problem "${slug}" (for "${name}")`);
      if (q.difficulty[0] !== diff) throw new Error(`"${name}": we say ${diff}, LeetCode says ${q.difficulty}`);
      entries.push([problemId(t.id, name), { n: Number(q.questionFrontendId), slug, premium: q.isPaidOnly }]);
      problems.push(name);
    }
  }
}

const body = entries
  .map(([id, e]) => `  '${id}': { n: ${e.n}, slug: '${e.slug}', premium: ${e.premium} },`)
  .join('\n');

writeFileSync(OUT, `// GENERATED by scripts/leetcode-links.mjs. Do not edit by hand; re-run the script instead.

export const LEETCODE = {
${body}
};

export const leetcodeUrl = (slug) => \`https://leetcode.com/problems/\${slug}/\`;
`);

const premium = entries.filter(([, e]) => e.premium).length;
console.log(`Wrote ${entries.length} problems (${premium} Premium) to data/leetcode.js`);
